In [2]:
import pandas as pd

In [3]:
#Load Data set 
df= pd.read_csv('C:\\Users\\shivraj\\OneDrive\\Desktop\\Hospital_Row_Data.csv',header=0)

In [4]:
df.head()

,Timestamp,1. Age group / वयोगट,2. Gender / लिंग,3. Household size / घरातील सदस्यसंख्या,\n4. Family type / कुटुंब प्रकार,5. Residence area / राहण्याचे ठिकाण,6. Occupation of main earner / घरातील मुख्य कमावणाऱ्याचे व्यवसाय,7. Highest education in household / घरातील सर्वात उच्च शिक्षण,8. Ration Card / रेशन कार्ड,1. Which type of hospital did you choose for your recent treatment?\n तुमच्या अलीकडील उपचारासाठी तुम्ही कोणत्या प्रकारचे रुग्णालय निवडले?,...,11. Your total health expenditure during the last three months / मागील तीन महिन्यांतील तुमचा एकूण आरोग्य खर्च,1. Monthly household income / घरातील मासिक उत्पन्न\n,2. Did you have to borrow money or sell assets for treatment? / उपचारासाठी पैसे कर्जाने घ्यावे किंवा मालमत्ता विकावी लागली का?\n,3. Healthcare costs create financial hardship for your family. (Rate 1–5)\nआरोग्य खर्चामुळे तुमच्या कुटुंबावर आर्थिक ताण येतो. (१ ते ५ रेट करा),4. Rate your family’s financial stability after healthcare spending. (Rate 1–5).\nआरोग्य खर्चानंतर तुमच्या कुटुंबाची आर्थिक स्थिरता कशी आहे? (१ ते ५ रेट करा),"1. Enrolled in any health insurance/government scheme? / कोणत्यातरी आरोग्य विमा किंवा सरकारी योजनेत "" सहभागी "" आहात का? (उदा.: महात्मा ज्योतिबा फुले जनआरोग्य योजना, आयुष्मान भारत, PMJAY, Private Insurance)","2. Used insurance/government scheme for treatment? / उपचारासाठी विमा/सरकारी योजना "" वापरली "" का?",3. How much financial support did you receive from the health insurance or government scheme?\n(तुम्हाला विमा किंवा सरकारी योजनांमुळे किती प्रमाणात आर्थिक आधार मिळाला?)\n,4. Ease of accessing insurance/government benefits / विमा/सरकारी योजना मिळवणे किती सोपे आहे? ( मूल्यांकन द्या ),5. Trust in government and private health schemes to support your family financially (Give Rank)\nसरकारी आणि खासगी आरोग्य योजनेमुळे तुमच्या कुटुंबासाठी आर्थिक आधार मिळेल यावर किती विश्वास आहे? (मूल्यांकन द्या)
0,2026/02/24 1:59:12 PM GMT+5:30,60 and above,Female / महिला,5,Nuclear / लहान कुटुंब,Rural / ग्रामीण,Farming / शेती,Postgraduate / पदव्युत्तर,Orange / केशरी,Private hospital / खाजगी रुग्णालय,...,5000,"11,501 - 23,000",No / नाही,2. Low hardship / कमी ताण,4 . Good stability / चांगली स्थिरता,Yes / हो,Yes / हो,3. Moderate (मध्यम),2. Difficult / कठीण,3. Moderate trust / मध्यम विश्वास
1,2026/02/24 2:04:29 PM GMT+5:30,18–29,Male / पुरुष,4,Nuclear / लहान कुटुंब,Rural / ग्रामीण,Farming / शेती,Graduate / पदवी,Orange / केशरी,Private hospital / खाजगी रुग्णालय,...,0,"Less than 11,500",No / नाही,2. Low hardship / कमी ताण,5. Very good stability / खूप चांगली स्थिरता,Yes / हो,Yes / हो,5. Very high (फार जास्त),3. Neutral / मध्यम,4. High trust / जास्त विश्वास
2,2026/02/24 2:23:37 PM GMT+5:30,45-59,Female / महिला,3,Nuclear / लहान कुटुंब,Rural / ग्रामीण,Farming / शेती,Graduate / पदवी,Orange / केशरी,Private hospital / खाजगी रुग्णालय,...,4000,"11,501 - 23,000",No / नाही,2. Low hardship / कमी ताण,4 . Good stability / चांगली स्थिरता,Yes / हो,No / नाही,0. None (काहीही नाही),3. Neutral / मध्यम,3. Moderate trust / मध्यम विश्वास
3,2026/02/24 2:27:51 PM GMT+5:30,45-59,Female / महिला,10,Joint / एकत्र कुटुंब,Rural / ग्रामीण,Farming / शेती,Graduate / पदवी,Orange / केशरी,Private hospital / खाजगी रुग्णालय,...,6000,"More than 34,500",No / नाही,1. No hardship / अजिबात ताण नाही,4 . Good stability / चांगली स्थिरता,No / नाही,No / नाही,0. None (काहीही नाही),3. Neutral / मध्यम,2. Low trust / कमी विश्वास
4,2026/02/24 2:29:18 PM GMT+5:30,18–29,Male / पुरुष,5,Nuclear / लहान कुटुंब,Rural / ग्रामीण,Farming / शेती,Postgraduate / पदव्युत्तर,Orange / केशरी,Government hospital / सरकारी रुग्णालय,...,0,"11,501 - 23,000",No / नाही,2. Low hardship / कमी ताण,4 . Good stability / चांगली स्थिरता,Yes / हो,Yes / हो,4. High (जास्त),2. Difficult / कठीण,3. Moderate trust / मध्यम विश्वास

In [50]:
#Remove First Column (Timestamp) 
df=df.iloc[:,1:]

In [51]:
# Change Columns name for analysis 
name=['Age_group', 'Gender', 'Household_size', 'Family_type', 'Residence_area', 'Occupation_of_main_earner', 'Highest_education_in_household', 'Ration_Card_type', 'Type_of_hospital', 'Type_of_patient', 'Type_of_illness', 'Visits_per_month', 'Hospital_visit_cost', 'Consultation_fee', 'Medicine_cost', 'Diagnostics_cost', 'Travel_cost', 'Lost_income', '3_month_total_expenditure', 'Monthly_income', 'Borrowed_money', 'Financial_hardship', 'Financial_stability', 'Insurance_enrolled', 'Insurance_used', 'Financial_support_level', 'Ease_of_access', 'Trust_level']
df.columns = name

In [52]:
df.head()

,Age_group,Gender,Household_size,Family_type,Residence_area,Occupation_of_main_earner,Highest_education_in_household,Ration_Card_type,Type_of_hospital,Type_of_patient,...,3_month_total_expenditure,Monthly_income,Borrowed_money,Financial_hardship,Financial_stability,Insurance_enrolled,Insurance_used,Financial_support_level,Ease_of_access,Trust_level
0,60 and above,Female / महिला,5,Nuclear / लहान कुटुंब,Rural / ग्रामीण,Farming / शेती,Postgraduate / पदव्युत्तर,Orange / केशरी,Private hospital / खाजगी रुग्णालय,Outpatient (not admitted) / फक्त तपासणी किंवा...,...,5000,"11,501 - 23,000",No / नाही,2. Low hardship / कमी ताण,4 . Good stability / चांगली स्थिरता,Yes / हो,Yes / हो,3. Moderate (मध्यम),2. Difficult / कठीण,3. Moderate trust / मध्यम विश्वास
1,18–29,Male / पुरुष,4,Nuclear / लहान कुटुंब,Rural / ग्रामीण,Farming / शेती,Graduate / पदवी,Orange / केशरी,Private hospital / खाजगी रुग्णालय,Outpatient (not admitted) / फक्त तपासणी किंवा...,...,0,"Less than 11,500",No / नाही,2. Low hardship / कमी ताण,5. Very good stability / खूप चांगली स्थिरता,Yes / हो,Yes / हो,5. Very high (फार जास्त),3. Neutral / मध्यम,4. High trust / जास्त विश्वास
2,45-59,Female / महिला,3,Nuclear / लहान कुटुंब,Rural / ग्रामीण,Farming / शेती,Graduate / पदवी,Orange / केशरी,Private hospital / खाजगी रुग्णालय,Outpatient (not admitted) / फक्त तपासणी किंवा...,...,4000,"11,501 - 23,000",No / नाही,2. Low hardship / कमी ताण,4 . Good stability / चांगली स्थिरता,Yes / हो,No / नाही,0. None (काहीही नाही),3. Neutral / मध्यम,3. Moderate trust / मध्यम विश्वास
3,45-59,Female / महिला,10,Joint / एकत्र कुटुंब,Rural / ग्रामीण,Farming / शेती,Graduate / पदवी,Orange / केशरी,Private hospital / खाजगी रुग्णालय,Outpatient (not admitted) / फक्त तपासणी किंवा...,...,6000,"More than 34,500",No / नाही,1. No hardship / अजिबात ताण नाही,4 . Good stability / चांगली स्थिरता,No / नाही,No / नाही,0. None (काहीही नाही),3. Neutral / मध्यम,2. Low trust / कमी विश्वास
4,18–29,Male / पुरुष,5,Nuclear / लहान कुटुंब,Rural / ग्रामीण,Farming / शेती,Postgraduate / पदव्युत्तर,Orange / केशरी,Government hospital / सरकारी रुग्णालय,Inpatient (admitted) / रुग्णालयात भरती झालो होतो,...,0,"11,501 - 23,000",No / नाही,2. Low hardship / कमी ताण,4 . Good stability / चांगली स्थिरता,Yes / हो,Yes / हो,4. High (जास्त),2. Difficult / कठीण,3. Moderate trust / मध्यम विश्वास

In [53]:
# Function For replace unwanted symbol 
def replace_dash(x):
    try:
        x = str(x)
        return x.replace("–", "/").replace("â€“", "/")
    except:
        return x

# Apply Fucntion 
df['Occupation_of_main_earner'] = df['Occupation_of_main_earner'].apply(replace_dash)

In [54]:
# Replace value from specific row and column together 
df.loc[
    df['Type_of_hospital'] == 'Government hospital',
    ['Hospital_visit_cost', 'Consultation_fee', 'Diagnostics_cost']
] = 0

In [55]:
#Cleaning Special Characters and Bracket Text
import re

def clean(x):
    try:
        x = str(x)
        x = x.split("/")[0]              
        x = re.sub(r"\s*\(.*?\)", "", x)    
        return x.strip()
    except:
        return x

In [56]:
# Apply function 
for col in df.columns:
    df[col] = df[col].apply(clean)

In [57]:
# Function for Removing unwanted numbers/symbols
import re

def clean_illness(x):
    try:
        x = str(x)
        
        # Fix encoding (important)
        try:
            x = x.encode('latin1').decode('utf-8')
        except:
            pass
        
        # Keep only English words at beginning
        match = re.match(r'^[A-Za-z\s\-]+', x)
        if match:
            return match.group().strip()
        
        return x.strip()
    
    except:
        return x

df['Type_of_illness'] = df['Type_of_illness'].apply(clean_illness)

In [58]:
df.head()

,Age_group,Gender,Household_size,Family_type,Residence_area,Occupation_of_main_earner,Highest_education_in_household,Ration_Card_type,Type_of_hospital,Type_of_patient,...,3_month_total_expenditure,Monthly_income,Borrowed_money,Financial_hardship,Financial_stability,Insurance_enrolled,Insurance_used,Financial_support_level,Ease_of_access,Trust_level
0,60 and above,Female,5,Nuclear,Rural,Farming,Postgraduate,Orange,Private hospital,Outpatient,...,5000,"11,501 - 23,000",No,2. Low hardship,4 . Good stability,Yes,Yes,3. Moderate,2. Difficult,3. Moderate trust
1,18–29,Male,4,Nuclear,Rural,Farming,Graduate,Orange,Private hospital,Outpatient,...,0,"Less than 11,500",No,2. Low hardship,5. Very good stability,Yes,Yes,5. Very high,3. Neutral,4. High trust
2,45-59,Female,3,Nuclear,Rural,Farming,Graduate,Orange,Private hospital,Outpatient,...,4000,"11,501 - 23,000",No,2. Low hardship,4 . Good stability,Yes,No,0. None,3. Neutral,3. Moderate trust
3,45-59,Female,10,Joint,Rural,Farming,Graduate,Orange,Private hospital,Outpatient,...,6000,"More than 34,500",No,1. No hardship,4 . Good stability,No,No,0. None,3. Neutral,2. Low trust
4,18–29,Male,5,Nuclear,Rural,Farming,Postgraduate,Orange,Government hospital,Inpatient,...,0,"11,501 - 23,000",No,2. Low hardship,4 . Good stability,Yes,Yes,4. High,2. Difficult,3. Moderate trust

In [59]:
df = df.drop(df[df['Gender'] == 'Other'].index)

In [60]:
#Converting Text Ranges into Numeric Values 
import re

def convert_value(x):
    try:
        x = str(x)
        
        # Remove commas first
        x = x.replace(",", "")
        
        # Case 1: More than 5000 → 5000
        if "More than" in x:
            return int(re.findall(r"\d+", x)[0])
        
        # Case 2: 0-500 → 500
        if "-" in x:
            return int(x.split("-")[1])
        
        # Case 3: already number
        return int(x)
    
    except:
        return x

df['3_month_total_expenditure']=df['3_month_total_expenditure'].apply(convert_value)

In [61]:
#change data type
df['3_month_total_expenditure'] = pd.to_numeric(
    df['3_month_total_expenditure'], errors='coerce'
)

In [62]:
#check for missing value 
df.isnull().sum()

Age_group                         0
Gender                            0
Household_size                    0
Family_type                       0
Residence_area                    0
Occupation_of_main_earner         0
Highest_education_in_household    0
Ration_Card_type                  0
Type_of_hospital                  0
Type_of_patient                   0
Type_of_illness                   0
Visits_per_month                  0
Hospital_visit_cost               0
Consultation_fee                  0
Medicine_cost                     0
Diagnostics_cost                  0
Travel_cost                       0
Lost_income                       0
3_month_total_expenditure         1
Monthly_income                    0
Borrowed_money                    0
Financial_hardship                0
Financial_stability               0
Insurance_enrolled                0
Insurance_used                    0
Financial_support_level           0
Ease_of_access                    0
Trust_level                       0
dtype: int64

In [63]:
#fill missing value
df['3_month_total_expenditure']=df['3_month_total_expenditure'].fillna(df['3_month_total_expenditure'].mean())
df['Ease_of_access']=df['Ease_of_access'].fillna(df['Ease_of_access'].mode()[0])

In [64]:
# convert columns into numeric 
import re

def convert_to_number(x):
    try:
        x = str(x).strip().lower()
        
        # Yes / No
        if x in ["yes", "1. yes", "yes.", "y"]:
            return 1
        if x in ["no", "2. no", "no.", "n","nan","Not applicable"]:
            return 0
        
        # Fix encoding issues
        x = x.replace("â€“", "-").replace("–", "-").replace("--", "-")
        
        # Case: More than / Less than (handle comma numbers correctly)
        if "more than" in x or "less than" in x:
            num = re.findall(r"[\d,]+", x)   # capture full number like 11,500
            if num:
                return float(num[0].replace(",", ""))
        
        # Remove unwanted characters except digits and -
        x = re.sub(r"[^\d\-,]", "", x)
        
        # Remove commas
        x = x.replace(",", "")
        
        # Case: Range → midpoint
        if "-" in x:
            parts = [p for p in x.split("-") if p != ""]
            if len(parts) == 2:
                return (float(parts[0]) + float(parts[1])) / 2
        
        # Case: Single number
        if x.isdigit():
            return float(x)
        
        return 0
    
    except:
        return 0

In [65]:
#New data frame for numeric column 
cols=['Household_size','Visits_per_month', 'Hospital_visit_cost', 'Consultation_fee', 'Medicine_cost', 'Diagnostics_cost', 'Travel_cost','Monthly_income','Lost_income','Borrowed_money', 'Financial_hardship', 'Financial_stability', 'Insurance_enrolled', 'Insurance_used', 'Financial_support_level', 'Ease_of_access', 'Trust_level']
new_df = pd.DataFrame()

for col in cols:
    new_df[col + "_numeric"] = df[col].apply(convert_to_number)

In [66]:
#combination of data frame 
cols = [
    'Age_group', 'Gender', 'Household_size', 'Family_type',
    'Residence_area', 'Occupation_of_main_earner',
    'Highest_education_in_household', 'Ration_Card_type',
    'Type_of_hospital', 'Type_of_patient', 'Type_of_illness','3_month_total_expenditure'
]

df_selected = df[cols]

final_df = pd.concat([df_selected, new_df], axis=1)
print(final_df.head())
print(final_df.shape)

      Age_group  Gender Household_size Family_type Residence_area  \
0  60 and above  Female              5     Nuclear          Rural
1         18–29    Male              4     Nuclear          Rural
2         45-59  Female              3     Nuclear          Rural
3         45-59  Female             10       Joint          Rural
4         18–29    Male              5     Nuclear          Rural

  Occupation_of_main_earner Highest_education_in_household Ration_Card_type  \
0                   Farming                   Postgraduate           Orange
1                   Farming                       Graduate           Orange
2                   Farming                       Graduate           Orange
3                   Farming                       Graduate           Orange
4                   Farming                   Postgraduate           Orange

      Type_of_hospital Type_of_patient  ... Monthly_income_numeric  \
0     Private hospital      Outpatient  ...                17250.5
1     Private hospital      Outpatient  ...                11500.0
2     Private hospital      Outpatient  ...                17250.5
3     Private hospital      Outpatient  ...                34500.0
4  Government hospital       Inpatient  ...                17250.5

   Lost_income_numeric  Borrowed_money_numeric  Financial_hardship_numeric  \
0                    0                       0                         2.0
1                    0                       0                         2.0
2                    0                       0                         2.0
3                    0                       0                         1.0
4                    0                       0                         2.0

   Financial_stability_numeric  Insurance_enrolled_numeric  \
0                          4.0                           1
1                          5.0                           1
2                          4.0                           1
3                          4.0                           0
4                          4.0                           1

   Insurance_used_numeric  Financial_support_level_numeric  \
0                       1                              3.0
1                       1                              5.0
2                       0                              0.0
3                       0                              0.0
4                       1                              4.0

   Ease_of_access_numeric  Trust_level_numeric
0                     2.0                  3.0
1                     3.0                  4.0
2                     3.0                  3.0
3                     3.0                  2.0
4                     2.0                  3.0

[5 rows x 29 columns]
(299, 29)

In [67]:
#Convert float value into integer
final_df['Visits_per_month_numeric']=final_df['Visits_per_month_numeric'].round().astype(int)

In [68]:
# Fill 0 value with mode value
mode_val = final_df['3_month_total_expenditure'][final_df['3_month_total_expenditure'] != 0].mode()[0]

final_df['3_month_total_expenditure'] = final_df['3_month_total_expenditure'].replace(0, mode_val)

In [69]:
# Save dataframe into csv file 
final_df.to_csv("Hospital Data.csv", index=False)